### ISSUE TITLE
[RFC FS-1016] Revise the reserved keyword list

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#102]
This is the discussion thread for [RFC FS-1016 - Revise the reserved keyword list](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1016-unreserve-keywords.md), if needed

**Comment by dsyme** [comment]
We could also consider the status of the following, which are only keywords for compat with OCaml.  We could change them to be warnings that the ``--ml-compatibility`` flag need to be used, and make them non-reserved in a later release.

      ALWAYS, "asr"        ,INFIX_STAR_STAR_OP "asr";
      ALWAYS, "land"       ,INFIX_STAR_DIV_MOD_OP "land";
      ALWAYS, "lor"        ,INFIX_STAR_DIV_MOD_OP "lor";
      ALWAYS, "lsl"        ,INFIX_STAR_STAR_OP "lsl";
      ALWAYS, "lsr"        ,INFIX_STAR_STAR_OP "lsr";
      ALWAYS, "lxor"       ,INFIX_STAR_DIV_MOD_OP "lxor";
      ALWAYS, "mod"        ,INFIX_STAR_DIV_MOD_OP "mod";

**Comment by gmpl** [comment]
@dsyme Any good reason to keep <code>const</code> as reserved?
It's a common combinator name.

**Comment by smoothdeveloper** [comment]
@gmpl Microsoft/visualfsharp#1265 needs to be fixed first, it won't be backward compatible if it is not a keyword anymore.

Maybe you can use `konst` for the combinator?

**Comment by dsyme** [comment]
Closing as accepted for F# 4.1

**Comment by abelbraaksma** [comment]
@bmitc can you open a new language request with reserved keywords that you'd like to see gone? 

If accepted, it should be fairly quick to turn into an RFC and implement.
