### ISSUE TITLE
RFC FS-1020 Discussion - byref returns

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#115]
Discussion thread for [F# RFC FS-2020 - Byref Returns](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1020-byref-returns.md)

**Comment by Rickasaurus** [comment]
RFC Link seems to be broken.

**Comment by dsyme** [comment]
@Rickasaurus fixed, thank

**Comment by dsyme** [comment]
Closing as accepted for F# 4.1. Discussion may continue on this thread
