### ISSUE TITLE
How about adding labels for the RFC so people can see ones that need attention or are under implementation etc?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fslang-design#139]

**Comment by kurtschelfthout** [comment]
I like this idea. I think they should be labelled so that people can easily see what the best way is to make progress on an RFC, e.g.
* Discussion needed
* Investigation needed
* Ready for @dsyme to make a call on options/outstanding issues :)
* Ready for implementation
* Documentation needed

**Comment by dsyme** [comment]
Sure, sounds good

**Comment by neoeinstein** [comment]
![Labeling](http://i.giphy.com/blHWlFadiY9hu.gif)

**Comment by neoeinstein** [comment]
Done.
![Labeled](http://i.giphy.com/3oz8xTUmZABI3PGwDe.gif)
