### ISSUE TITLE
[RFC FS-1028 Discussion] - Implement Async.StartImmediateAsTask

### ISSUE THREAD

**Issue by OnurGumus** [fsharp/fslang-design#153]
This is the discussion thread for RFC [FS-1028.](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1028-Implement%20Async.StartImmediateAsTask.md)

**Comment by dsyme** [comment]
@OnurGumus Did you get a chance to implement this?

**Comment by OnurGumus** [comment]
@dsyme apologies, this should have been a simple method, but I lost my focus. I will try to implement this weekend if I can.

**Comment by dsyme** [comment]
@OnurGumus Great!!

**Comment by OnurGumus** [comment]
@dsyme  done with https://github.com/Microsoft/visualfsharp/pull/2534

**Comment by cartermp** [comment]
This is implemented as shipped, with no apparent need for discussion. Closing!
