### ISSUE TITLE
Struct Union Compilation Failure

### ISSUE THREAD

**Issue by huwman** [fsharp/fslang-design#159]
When attempting to compile a struct union with 2 cases in which the cases have the same arity and field types it fails with 'error: Error in pass2 for type TestUnion, error: duplicate entry '.ctor' in method table'.

I believe it is trying to compile a type with the following ctors ():
`TestUnion(x : int, tag : int)`
and
`TestUnion(y : int, tag : int)`

Instead these constructors should be combined something as follows, to illustrate the logic :
```
TestUnion(value : int, tag : int) =
    _tag <- tag
    // Assign correct field based on tag
    if tag = 0 then _x <- value else _y <- value
```

**Comment by smoothdeveloper** [comment]
@huwman it seems like a bug and more relevant to https://github.com/Microsoft/visualfsharp/ repository.

Can you post detailed issue there, with minimum code sample to reproduce.

**Comment by dsyme** [comment]
@huwman Yes, this is a bug, please add to the visualfsharp repo
