### ISSUE TITLE
Native support for Task and Task<'T>

### ISSUE THREAD

**Issue by dustinmoris** [fsharp/fslang-design#208]
Hi,

I was wondering if it would make sense to add native support for Tasks in F# which doesn't require to convert a `Task` into an `Async` object back and forth all the time.

Given that most libraries in .NET (almost everything) works with Tasks (when it supports async) I think it almost doesn't make sense for having `Async` today other than backwards compatibility. In other words, I suggest if we could have something like `task {}` in F# which deprecates `async {}` in the future?

FSharpX has a task computation expression and someone else has further improved it in [this GitHub repository](https://github.com/buybackoff/FSharpAsyncVsTPL/blob/master/FSharpTasks/TaskBuilder.fs), which [claims to be a lot more faster](https://stackoverflow.com/questions/35762747/performance-of-async-in-f-vs-c-sharp-is-there-a-better-way-to-write-async/35766979#35766979) than having to constantly convert between Task and Async back and forth.

What do you think of it and what caveats does it have which I might be missing at this point?

**Comment by rmunn** [comment]
The process for submitting new ideas for the F# language is to first create an issue in the https://github.com/fsharp/fslang-suggestions repo. Then if that issue is marked "approved in principle", you create an RFC and an issue in this repo for discussing the implementation. See https://github.com/fsharp/fslang-design/blob/master/README.md for more details.

**Comment by rmunn** [comment]
Also, this may be the same as the existing https://github.com/fsharp/fslang-suggestions/issues/559 proposal. If it isn't the same, you can create another issue in https://github.com/fsharp/fslang-suggestions, but you should describe how it differs from existing, similar proposals like https://github.com/fsharp/fslang-suggestions/issues/559.

**Comment by dustinmoris** [comment]
Thank you. I have created [the suggestion there](https://github.com/fsharp/fslang-suggestions/issues/581).
