### ISSUE TITLE
Missing using static equivalent in F# 

### ISSUE THREAD

**Issue by NinoFloris** [fsharp/fslang-design#216]
Basically missing this suggestion in this repo:
 https://fslang.uservoice.com/forums/245727-f-language/suggestions/6958404-allow-opening-of-static-classes-matching-the-c-d

**Comment by rmunn** [comment]
That suggestion has been migrated to https://github.com/fsharp/fslang-suggestions/issues/383

**Comment by cartermp** [comment]
Closing as dupe of the fslang-suggestions issue
