### ISSUE TITLE
FSharp.Core planning note

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#232]
The visualfsharp repo has a couple of pull requests for FSharp.Core.   Before pulling these we wanted to pause for a moment and look at where we are with planning future additions, and get full community visibility and input on next steps.

Please discuss. Relevant resources are:

* [Approved-in-principle library suggestions](https://github.com/fsharp/fslang-suggestions/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22area%3A%20library%22%20label%3A%22approved-in-principle%22%20)
* [Other library suggestions](https://github.com/fsharp/fslang-suggestions/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22area%3A%20library%22%20-label%3A%22approved-in-principle%22%20)
* [F# community twitter conversation](https://twitter.com/dsyme/status/930489150050054144)
* [F# 2.0-era design document for FSharp.Core](https://github.com/fsharp/fsfoundation/blob/gh-pages/specs/archive/FSharp-2.0-EarlyLibrarySpec-v34.docx)

### Proposal: 4.4.3.0 tactical release

It is proposed by @KevinRansom that we do a version 4.4.3.0 tactical release of FSharp.Core with at least the two PRs:

* [F# RFC FS-1028 - Implement Async.StartImmediateAsTask](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1028-Implement%20Async.StartImmediateAsTask.md)

* [F# 4.x: Add ToFSharpFunc overloads for Func<...>, especially for .NET Core](https://github.com/Microsoft/visualfsharp/pull/3013)

* [Add System.Collections.ICollection implementations to F# set/map](https://github.com/Microsoft/visualfsharp/pull/2085)

This seems reasonable.  @KevinRansom would also like to publish incremental updates more frequently in the future (Again reasonable).

### On the Slate 

1. The top actionable requests are 

   a. [add “task { … }” ](https://github.com/fsharp/fslang-suggestions/issues/581)
   b. [add more immutable collections](https://github.com/fsharp/fslang-suggestions/issues/619)
   c. improve interoperability with C#

2. Additional approved items of note:

   a. [string module enhancements](https://github.com/fsharp/fslang-suggestions/issues/112)
   a. [Deprecate the default definition of (!) and ask users to use .Value instead or use a compat module](https://github.com/fsharp/fslang-suggestions/issues/569)
   b. [Seq/Array/List.transpose](https://github.com/fsharp/fslang-suggestions/issues/106)

### New requests:

Noting these requests not yet tracked by suggestions:
1. Result module of useful functions
2.  ``option { … }`` and ``result { … }`` computation expressions
3.  ``AsyncResultCell`` (“TaskCompletionSource but for Async”)

**Comment by ijsgaus** [comment]
When we can see strategical release?

**Comment by ForNeVeR** [comment]
@ijsgaus while I sympathize to your suggestion about more open "strategical" planning, I don't think it's the proper place to discuss it. Here we're talking about FSharp.Core release, and [the list](https://github.com/fsharp/fslang-suggestions/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22area%3A%20library%22%20label%3A%22approved-in-principle%22%20) Don mentioned is about FSharp.Core library additions / changes. It's not about language (or ecosystem for that matter) evolution.

Though I'm not sure where we, the community, should discuss the language evolution strategy. Probably @cartermp could tell?

**Comment by cartermp** [comment]
This repository, but not this issue, is a potential place. But I'm not sure what would be gained by such a discussion. Evolution is a straightforward and well-defined process:

1. Suggestion made.
2. Discussion had.
3. Approval given, if the suggestion seems good enough.
4. RFC drafted.
5. RFC discussed and revised based on feedback from others.
6. Implementation started.
7. Feedback loop with changes in the implementation, and RFC as needed.
8. Once the implementation is of acceptably high quality, it is merged.
9. After a bundle of features are merged, and they make sense together, a new version is declared.

I don't see this process changing much.

**Comment by wallymathieu** [comment]
Having `option` and `result` computation expressions in core would be nice. @jack-pappas has done some work that perhaps could reused (as pointed out by @vasily-kirichenko) : [ChoiceBuilder](https://github.com/jack-pappas/ExtCore/blob/42d629bc434248f77c2a8fc663b92167079d071f/ExtCore/Control.fs#L852) (since it's basically a computation expression implementation for Result)

**Comment by cartermp** [comment]
Closing old discussion - we've shipped a few FSharp.Core releases since now, and we're working towards what a 5.0 release of the library and language would look like on a per-feature basis, which I would expect in the fslang-suggestions repo
