### ISSUE TITLE
[RFC FS-1042 Discussion] Add transpose

### ISSUE THREAD

**Issue by PatrickMcDonald** [fsharp/fslang-design#236]
Discussion for https://github.com/fsharp/fslang-design/blob/master/FSharp.Core-4.4.3.0/FS-1042-add-seq-transpose.md

**Comment by PatrickMcDonald** [comment]
One edge case where transpose is implemented inconsistently is transposing a list of empty lists

    Assert.AreEqual([], List.transpose [[]])
    Assert.AreEqual([[]], List.transpose [[]; []])

    // array of empty arrays - m x 0 array transposes to 0 x m (i.e. empty)
    Assert.AreEqual([| |], Array.transpose [| [||] |])
    Assert.AreEqual([| |], Array.transpose [| [||]; [||] |])

I suppose whatever is done should be consistent, does it matter if we return a list containing an empty list or simply an empty list?

**Comment by rmunn** [comment]
Wolfram Alpha seems to agree. Compare [a normal transposition](https://www.wolframalpha.com/input/?i=transpose+%7B%7Ba,+b,+c%7D,+%7Bx,+y,+z%7D%7D) to [a transposition of two empty rows](https://www.wolframalpha.com/input/?i=transpose+%7B%7B%7D,+%7B%7D%7D). The latter returns `{}`, the notation for an empty matrix.

**Comment by cartermp** [comment]
Closing old discussion - this is implemented and there doesn't appear to be much to discuss at this point
