### ISSUE TITLE
[RFC FS-1045] Add Func overloads for FuncConvert.ToFSharpFunc

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#247]
Discussion thread for https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1045-func-to-fsharpfunc-overloads.md

**Comment by wallymathieu** [comment]
Seems like a nice change to simplify interop.

**Comment by cartermp** [comment]
Closing as this is implemented and shipping as-is
