### ISSUE TITLE
[RFC FST-1004] - Versioning discussion

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-design#250]
This is for this RFC: https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1004-versioning-plan.md

In the RFC, there are [two options](https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1004-versioning-plan.md#options-for-fsharpcore) for the handling of FSharp.Core.  I'd like to get feedback on that.

**Option 1: Version in lockstep with the F# Language**, is favored by @dsyme as per [this comment](https://github.com/Microsoft/visualfsharp/issues/4113#issuecomment-352761522):

> There's a lot of simplicity value to keeping the versions aligned. So I think we should probably make it that from 4.5 onwards F# minor language revisions can just be "small" or even empty (i.e. F# 4.8 might be the same language as F# 4.7 with some improvements/adjustments to FSharp.Core).

**Option 2: Version independently from the F# language**, is favored by @KevinRansom as per a discussion him and I had, which I documented in the RFC.

Both are centered around a central problem, which is that we can (and likely will) receive improvements to the F# core library (beyond bug fixes) faster than improvements and new features in the F# compiler.

@dsyme suggests that we should just rev the F# language version when a sufficient number of changes are made to the F# core library, which would satisfy the desire to rev FSharp.Core when these changes are merged.  @KevinRansom, what are your thoughts?

Also tagging @isaacabraham, as this was a point he brought up in the [related VisualFSharp issue](https://github.com/Microsoft/visualfsharp/issues/4113).

**Comment by jackfoxy** [comment]
I like option 2. From a user perspective quicker access to performance improvements trumps versioning confusion.

**Comment by cartermp** [comment]
Closing old discussion - this is implemented
