### ISSUE TITLE
Compilation messages as in Reason/Elm

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fslang-design#252]
See here: https://reasonml.github.io/blog/2017/08/25/way-nicer-error-messages.html

**Comment by forki** [comment]
We did already a lot on that front. Please contribute by listening concrete cases and concrete improvement suggestions in the visualfsharp repo. /cc @isaac_abraham

**Comment by forki** [comment]
I didn't mean you should close it. Just that we need to be more concrete -
it's big efforts and we are right in the middle of it.

Am 28.01.2018 19:36 schrieb "MatthiasSchuster" <notifications@github.com>:

**Comment by isaacabraham** [comment]
Here's the other issue https://github.com/Microsoft/visualfsharp/issues/1103

**Comment by ShalokShalom** [comment]
@isaacabraham Thanks, I will look into it. 

@forki The issue is, that the actual tooltips tell us, newbies, very less: They are more confusing to me as anything else. Those compilation messages might improve the situation and could potentially even improve the tooltips which are provided by Ionode.

**Comment by forki** [comment]
@ShalokShalom look I'm on of the guys who did a lot of the work on https://github.com/Microsoft/visualfsharp/issues/1103 - I know that we need to improve the situations for newcomers. That's why I'm working on that part

**Comment by isaacabraham** [comment]
@ShalokShalom we know about it - please help by creating errors and linking to 1103 that explain what error it was, and how it can be improved - what would you expect to see, what was the actual solution etc. etc. - it's really helpful getting issues raised from developers with different levels of experience, and especially beginners.

**Comment by ShalokShalom** [comment]
It seems like a lot is already finished and I like to try 4.2 ^-^

**Comment by forki** [comment]
Ionide is already using many of the new error messages

**Comment by ShalokShalom** [comment]
Does this apply also to the type mismatches?

**Comment by forki** [comment]
No there is not much suggestion improvement happening there yet.

Am 29.01.2018 18:37 schrieb "MatthiasSchuster" <notifications@github.com>:

**Comment by ShalokShalom** [comment]
Ah ok fine. When will this land?
Thanks a lot

**Comment by forki** [comment]
Oh I meant no we don't have really good suggestions for type errors yet. We
need samples where people think "wtf is this" - and then we can try to
improve.

Am 29.01.2018 19:01 schrieb "MatthiasSchuster" <notifications@github.com>:

**Comment by ShalokShalom** [comment]
Well, in general, all and everything where just "this is type x, it should be type y" is mentioned. 
Especially for more complex flows is this quite challenging. 
How do other languages that?

**Comment by forki** [comment]
There are special cases where we try to identify common issues like:
https://github.com/Microsoft/visualfsharp/pull/4255

Am 29.01.2018 20:14 schrieb "MatthiasSchuster" <notifications@github.com>:

**Comment by isaacabraham** [comment]
@ShalokShalom Find a single "wtf" example, create an issue on the main repo with description as per 1103 - that's really the best way to start a dialog on this. There are so many ways that types can clash, and I think that just having an issue along those lines won't get anywhere - it's just too broad.

**Comment by ShalokShalom** [comment]
Thanks a lot, I will do so.

**Comment by voronoipotato** [comment]
I think any problem which only has one solution should have the solution in the error message. 

I ran across one the other day
```
> type T = (int * int) | (bool * int);;

  type T = (int * int) | (bool * int);;
  ---------------------^

stdin(1,22): error FS0010: Unexpected symbol '|' in member definition
>
```

Unexpected symbol really makes it sound like what I was trying to do was absurd. In reality I just wanted to have a sum of two tuples. The true problem is that must name everything, not that you can't mix tuples and sum types but here Unexpected symbol '|' makes it sound like I can't.

**Comment by isaacabraham** [comment]
Sounds reasonable! Can you raise a separate issue for this, and tag it with the overall tracking issue? Cheers.
