### ISSUE TITLE
[RFC FS-1047 discussion] - match! (match-bang) syntax for computational expressions

### ISSUE THREAD

**Issue by jwosty** [fsharp/fslang-design#255]
Discussion for fslang-suggestions [#572](https://github.com/fsharp/fslang-suggestions/issues/572). RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1047-match-bang.md

**Comment by abelbraaksma** [comment]
Some questions: 

What are the legal places where `match!` can be placed? Can it be nested? 

The example shows usage with `async`, I assume it is going to be available with any CE, like `seq`? Could it also work with `yield!`? And how would it desugar inside a return, or is that an illegal place?

**Comment by jwosty** [comment]
@abelbraaksma Of course.

1) `match!` can only be included inside a computation expression. The branches of a `match!` will be computation expressions, meaning `match!` _can_ be nested.
2) `match!` will work with any computation builder, not just `async`.
3) I don't believe it it is legal inside a return. (I will have to double check this)

Basically, it follows the exact same rules as `let!`+`match`. They are 100% syntactically interchangeable; anywhere you can/can't put a `let!`+`match`, `match!` will behave the same.
