### ISSUE TITLE
[RFC FS-1048 discussion] - Extend ComputationExpression builders with Map : m<'a> * ('a -> 'b) -> m<'b>

### ISSUE THREAD

**Issue by jwosty** [fsharp/fslang-design#258]
Original suggestion: https://github.com/fsharp/fslang-suggestions/issues/36
RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1048-ce-builder-map.md

EDIT: I pasted the wrong file into the PR; the correct RFC will be coming soon.

**Comment by rmunn** [comment]
Something to consider is whether this should also apply to `let!` followed by `yield`, as well as `let!` followed by `return`. Since both `yield` and `return` have type `'T -> M<'T>`, they are essentially the same operation from a monadic point of view, and `let!` followed by `yield` could also be compiled to `map`. But do `yield` and `return` have the same semantics from the point of view of the programmer using a CE builder? E.g., would this be meaningful?

```fsharp
seq {
    let! x = someSeqProducingFun()
    yield g x
    let! y = anotherSeqProducingFun()
    yield h y
}
```

One major difference between `yield` and `return`, of course, is the intended usage in CEs: `return` is intended to be used once, for a CE that conceptually returns "a single value" (for whatever "value" and "single" mean in that given CE), such as an `async`. While `yield` is intended to be called multiple times, in CEs that conceptually return multiple values, like `seq`. So the ultimate question is, is it meaningful to have multiple `let!` -> `yield` operations (as in the above) translated to `map` in a CE such as `seq`?

**Comment by davidglassborow** [comment]
To quote https://fsharpforfunandprofit.com/posts/computation-expressions-builder-part1/#introducing-yield

> At this point you might be wondering: if return and yield are basically the same thing, why are there two different keywords? The answer is mainly so that you can enforce appropriate syntax by implementing one but not the other. For example, the seq expression does allow yield but doesn’t allow return, while the async does allow return, but does not allow yield, as you can see from the snippets below.
> In fact, you could create slightly different behavior for return vs. yield, so that, for example, using return stops the rest of the computation expression from being evaluated, while yield doesn’t.

> More generally, of course, yield should be used for sequence/enumeration semantics, while return is normally used once per expression. (We’ll see how yield can be used multiple times in the next post.)

**Comment by gusty** [comment]
Apart from style conventions regarding ``return`` and ``yield``, I think there is technically a difference regarding how Custom Operations maintain variable space.

**Comment by davidglassborow** [comment]
cc @dsyme

**Comment by jwosty** [comment]
@rmunn Hmm, good point, that's an asymmetry. About the chaining concern first, IIRC, this next code block would get compiled like so, no?

```fsharp
// sugared
builder {
    let! x = xexpr
    return f x
    let! y = yexpr
    return g y }
// desugared
builder.Bind(xexpr, fun x ->
    builder.Combine
       (builder.Return(f x),
        builder.Bind(fun y ->
            builder.Return(g y)
        )
    )
)
```

I think this should get transformed as:

```fsharp
builder.Combine(builder.Map(fun x -> f x),
                builder.Map(fun y -> g y))
```

To do this, the compiler would have to know that this variable is only being used in the next immediate `return` -- so if the snippet above were to use `x` anywhere else in the expression, this transformation could not be made (which I think makes sense; it's not following the semantics of `map` any more).

As for the other issue, what if we introduce a `MapYield` method as well? That way, it would be completely optional, and could have different semantics than `Map`. Come to think of it, maybe we should call "Map" "MapReturn" instead.

**Comment by jwosty** [comment]
Any more thoughts on this?

**Comment by jwosty** [comment]
Just noting that I have no inclinations to implement this myself -- I'm only helping it along by writing an RFC. If anyone wants to start a PR, be my guest

**Comment by cartermp** [comment]
@mistiara That would have to be considered, yes.

**Comment by TD5** [comment]
It's probably be worth thinking about [how this interacts with `Apply`](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1063-support-letbang-andbang-for-applicative-functors.md).

I suspect we want `let! ... return ...` to be desugared by `MapReturn` if it is defined, else `Apply` & `Return` if they are defined, else `Bind` and `Return`.

**Comment by jwosty** [comment]
I just re-read over [FS1063](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1063-support-letbang-andbang-for-applicative-functors.md), and this RFC is _almost_ now a sub-case of that RFC. I think that this RFC should propose to emit methods called `BindReturn` and `BindYield` (instead of `MapReturn` and `MapYield`) for consistency with FS-1063.

**Comment by jwosty** [comment]
I just read over [FS-1063](https://github.com/fsharp/fslang-design/issues/335) ([RFC](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1063-support-letbang-andbang-for-applicative-functors.md)). If I am not mistaken, it now covers the cases that this RFC (FS-1048) address. Closing as this RFC is now redundant.
