### ISSUE TITLE
FS-1054  - permit undentation on `[` ... `]` and `[|` ... `|]`

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#300]
Discussion thread for https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1054-undent-list-args.md

**Comment by wallymathieu** [comment]
Url should be https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1054-undent-list-args.md

**Comment by wallymathieu** [comment]
I've been bothered slightly by the above indentation rules. It makes intuitive sense from a programmer point of view.

**Comment by rmunn** [comment]
Another place where I've found the current rules annoying is in writing Expecto tests. My unit test files usually look like:

```fsharp
let apiTests = testList "API tests" [
    testCase "First test" <| fun _ ->
        // First test
    testCase "Second test" <| fun _ ->
        // Second test
]
```

With this indentation style, I have to ignore a lot of FS0058 warnings when I compile my tests. I'm glad to see that I won't have to ignore those warnings any more: they might actually indicate a bug in a different part of the code, so ignoring them removes that useful feedback, but I was getting tired of the false-positive indentation warnings in my unit test compilation output.

**Comment by smoothdeveloper** [comment]
@dsyme are we considering making it flexible for method parameter lists?

```fsharp
type TestParens (
  a : int,
  b : string) =
  member x.Foo(
    c
    , d
    ) = a, b, c, d
```
this prints FS0058 a few times:

> warning FS0058: Possible incorrect indentation: this token is offside of context started at position (45:17). Try indenting this token further or using standard formatting conventions.

**Comment by cartermp** [comment]
@smoothdeveloper That is out of scope for this feature. Could you submit an issue on the suggestions repo?

**Comment by cartermp** [comment]
Closing as this the feature is complete and it doesn't appear to be controversial to relax this class of indentations.
