### ISSUE TITLE
Tracking issue for nameof RFC

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-design#377]
https://github.com/fsharp/fslang-design/blob/master/preview/FS-1003-nameof-operator.md

The RFC isn't really an RFC: no design has actually been written.

Given this an numerous issues we identified in the feature, it is under the `preview` folder and will remain there until a design is written for it.

**Comment by dsyme** [comment]
I've updated the RFC. It can still be improved but it now lists all known issues (unresolved issues post preview) and the corner cases we've recently identified.
