### ISSUE TITLE
RFC FS-1046 is assigned twice

### ISSUE THREAD

**Issue by inosik** [fsharp/fslang-design#410]
While looking for the specs for the "Wildcard self identifiers" feature, I noticed that FS-1046 was already assigned before, for ["Consistent tuple types"](https://github.com/fsharp/fslang-design/blob/6229e6048ad49ec2b1820f5211703c4bf6220730/FSharp-4.1b/FS-1046-consistent-tuple-types.md).

**Comment by dsyme** [comment]
We'll put this down as a quirk of history
