### ISSUE TITLE
[RFC FS-1087] Discussion thread for task/state-machines/resumable-code RFC

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#455]
Discussion thread for [F# RFC FS-1087 - Resumable state machines and task builder](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1087-resumable-code-and-task-builder.md)

**Comment by cartermp** [comment]
I don't see mention of this in the PR and the implementation is rather large. Are the well-known intrinsics public? I think for something this large they should stay internal only for a while to account for any churn. I'm skeptical that we'll "get it right" on the first go and won't have a desire to adjust them afterwards.

**Comment by dsyme** [comment]
> Are the well-known intrinsics public? 

Yes they are.  They really need to be for testing purposes - it's very difficult if they aren't.

We should get the design right before it goes out of preview. 

What's our policy for FSHarp.Core surface area changes for preview-only features (assume the compiler intrinsics are marked "Experimental" or "only use in preview" or whatever we can do now).

I'm ok with the whole thing being in preview a fair time (for example I'm as concerned about the use of SRTP in Tasks.fs as I am about the intrinsics - and that's also FSharp.Core surface area).

I could sort of see us taking the "task" support out of preview first, though I'm not sure that gains us that much, as if the inlined code coming from FSharp.Core must conform to the resumable code spec.  It just means that if there are corner cases in the resumable code implementation *not* exposed by Tasks.fs then we could adjust that at a later point.

As an aside, I would like to use this for:
* compiling list computation expressions to more efficient code
* compiling array computation expressions to more efficient code
* `option { .. }`
* `result { .. }`

The first two cases give 4x speedup or more for some basic list/array constructions, see https://github.com/dotnet/fsharp/blob/92415de183daf8c6874a52b695d1da7ae6bb595e/BenchmarkDotNet.Artifacts/results/TaskPerf.ArrayBuilder-report-github.md for example

I may also look if there's a way to reimplement a 100% compatible `async { ... }` with this

**Comment by cartermp** [comment]
This would require the following then, yes:

```fsharp
[<Experimental("Experimental library feature, requires '--langversion:preview'")>]
```

Every new construct in FSharp.Core that is a part of a preview language feature needs to be decorated with this (unless custom work is done in the compiler itself to only light it up recognition of that construct and error out appropriately). This allows us to make a breaking change if we need, since previews are subject to breaking changes. Once that attribute goes away and we ship something, it cannot change.

**Comment by dsyme** [comment]
Regarding the faster `list { .. .}` and `array { .. }` for computed array/list....

Those have been known for a while in a different setting, where the difference between seq { .. } |> Seq.toArray and a builder that writes into a ResizeArray then calls ToArray is quite large.  Someone wrote a normal F# builder for that, I'll dig it out and add it as a perf comparison.  I'm not certain we're gaining much over that normal builder.

But the F# computation expression list `[ .. ]`   can be made even faster, if we put this technique in FSharp.Core (or else reveal the "mutate the end of a freshly allocated list" hack used in FSHarp.Core for fast list creation out as a compiler-known intrinsic.) That is, the operation of `[ ... ]` would now be to mutate the end of the list as it trundles along.

Consider `[ for x in 1 .. 3 do yield x; yield x+1 ]`. So this is going to be a struct state machine initially holding two registers (mutable fields) 
1. the last cons cell in the list being built 
2. a handle to the cons cell that forms the front of the list

* When the first yield happens, we create a cons cell and put it in both, the tail is not yet initialized

* When the second and later yields happen, we create another cons cell, put it in the tail of (1), and update (1) to be the new end cell (edited) 

* Then when the code is finished the list is ready to go, we just set the tail of (1) to the empty list and return (2). 

Then no `ResizeArray` is needed, and no `Seq.toList`.

**Comment by gusty** [comment]
> or else reveal the "mutate the end of a freshly allocated list" hack used in FSHarp.Core for fast list creation out as a compiler-known intrinsic.

I would like to have this available, maybe in an "Unsafe Primitives" module.

**Comment by dsyme** [comment]
Yes, it would be reasonable to add this to an Unsafe or Unchecked module.

Indeed all the resumable state machine primitives could be similarly named.

**Comment by cartermp** [comment]
With the caveat that it's protected with `Experimental` until the API is stable :)

**Comment by dsyme** [comment]
@cartermp Yup, but asepcts of the mechanism is basically unchecked, e.g. the `__resumeAt` can be cheated by using an arbitrary integer for the destination. The code won't actually be unverifiable, and it will be the equivalent of a drop-through, but likely warrants an Unchecked.  I'll add a note to the RFC

**Comment by smoothdeveloper** [comment]
Regarding ["Limitation - No asynchronous tailcalls"](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1087-resumable-code-and-task-builder.md#limitation---no-asynchronous-tailcalls), is emitting a warning considered?

this is akin to another gotcha quoted from http://tomasp.net/blog/csharp-async-gotchas.aspx/

> the most common gotcha is that tail-recursive functions must use return! instead of do! to avoid leaks

It would be great to have warnings for those.

**Comment by SteveGilham** [comment]
Seeing "resumable Tasks" makes me think of the old Workflow Foundation.  Would it be expected that the machine state could be pickled and later restored?

**Comment by dsyme** [comment]
> Seeing "resumable Tasks" makes me think of the old Workflow Foundation. Would it be expected that the machine state could be pickled and later restored?

Semantically, I think there's nothing you can do with resumable tasks that you can't already do with existing workflows.  Existing workflow states can be pickled with some care (you need to to private reflection over the workflow state and captured values, or else make the state explicit in monadic actions)

It might in theory help to have the state organised in a way that more closely matches the structure of the code (one state machine object per "foo { ... }") but this can also make things tricker, e.g. there can be multiple not-yet-active fields for locals in the state machine.

For these reasons I wouldn't recommend thinking of this as a semantic feature at all, but rather just a performance feature.  I'll add that to the RFC.

**Comment by dsyme** [comment]
BTW the best worked out framework for persisted workflows that I know of is the Angara framework, open sourced here: https://github.com/microsoft/Angara.Flow/blob/master/docs/content/Execution.md

**Comment by dsyme** [comment]
> Regarding "Limitation - No asynchronous tailcalls", is emitting a warning considered?
> 
> this is akin to another gotcha quoted from http://tomasp.net/blog/csharp-async-gotchas.aspx/
> 
> the most common gotcha is that tail-recursive functions must use return! instead of do! to avoid leaks
> 
> It would be great to have warnings for those.

Good point on all of these.

**Comment by NatElkins** [comment]
I have a design question.  Is there any reason magic naming (i.e. `__expand_`) was used over, say, attributes?  Was it ease of implementation, or because of limitations of attributes?  Or something else?

**Comment by dsyme** [comment]
> I have a design question. Is there any reason magic naming (i.e. __expand_) was used over, say, attributes? Was it ease of implementation, or because of limitations of attributes? Or something else?


This is all still open for discussion.  I'll add it to the RFC

Basically, attributes aren't allowed on expression-locals in F# today, and I was looking for something sufficiently weird to highlight that this is a here-be-dragons compiler optimization feature.

**Comment by baronfel** [comment]
What would the ideal representation of these features in your view be @dsyme? I could see some value is a section around 'considered-but-rejected', 'ideal-but-unimplementable', and 'compromise-current-state' syntax if there were language-restricted reasons you landed on this particular syntax.  That might point towards future language features that could be fleshed out?

**Comment by abelbraaksma** [comment]
> Basically, attributes aren't allowed on expression-locals in F# today, and I was looking for something sufficiently weird 

@dsyme There's a design suggestion open: https://github.com/fsharp/fslang-suggestions/issues/848, which, if supported and implemented, may allow this new feature to be triggered with attributes as opposed to magical names.

**Comment by cartermp** [comment]
I would far prefer attributes over bizarre keywords, mostly since there's already a design precedent around them being used to augment things (byref structs, readonly structs, struct DUs, struct records, etc.)

**Comment by NatElkins** [comment]
I don't even know if the CLR would allow attributes on expression locals.  Allowing attributes on local functions isn't quite the same thing, since methods are acceptable targets for attributes today.  Here is the closest C# language suggestion I could find: https://github.com/dotnet/csharplang/issues/2478 .  I think there might be incompatibility with the AttributeUsageAttribute which wouldn't be able to cover the expression local

I do wonder if instead of using special names, some combination of attributes (on things that can have attributes) and types as annotation could be used.  For example, in the case of `__stack_step ` using AttributeUsage.ReturnUsage on the expanded function and a special type for what `__stack_step` represents to restrict its usage to a particular pattern.

Also there are some cases I was wondering if functions can be used to restrict usage rather than asking the programmer to adhere to a particular pattern.  The case I'm thinking of here is

```fsharp
    if __useResumableStateMachines then
        __resumableStateMachine
            { new SomeStateMachineType() with 
                member __.Step ()  = 
                   <resumable code>
            }
    else
        <dynamic-implementation>
```

Is there any reason a function that itself takes two functions (one for the compilation case, the other for the dynamic case) can't be used to enforce this pattern?

To be fair, I have no idea what the implementation cost is to do it in that way vs the way it currently is.

**Comment by dsyme** [comment]
> Is there any reason a function that itself takes two functions (one for the compilation case, the other for the dynamic case) can't be used to enforce this pattern? Or an abstract class/interface that has two methods, one for each case?

Any of these would be ok-ish, they are all problematic.  I think the if/then/else lends itself easily to `#if` of the `if` branch if you want to compile and thest only the regular-code-dynamic-execution implementation.

> I don't even know if the CLR would allow attributes on expression locals. 

This is correct, I believe it's not allowed in the .NET metadata format which is why we don't support it for expression locals in F#.  We could make an exception for these particular attributes in F# code but that feels as hacky as anything else.

The current approach is definitely hacky though - I'm not denying that - and am open to suggestions.  It has some advantages (as noted in the RFC) - I don't think we even want this feature to feel "part of the language", even less so than `[<Struct>]`.  

It's possible we could continue to decompose it into micro features like C# did with byrefs, span etc.    But I think that would lead naturally to an explosion of complexity for little gain.  

For example, we could allow something like this as a first class language feature:
```
let f () = 
            { [<Struct]
              new IComparable with 
                member __.CompareTo (x)  = ... }
```
To be effective this construct would need to imply a local type definition `T when T:struct and T :> IComparable`.  But then we'd need a new rule checking that this locally implied type was eliminated (utilised) immediately (as in the `After` code in the encoding in the RFC).  That would be yet another new rule (checking no escape of local struct types).  Yet the feature doesn't seem to be so useful and has never been requested to my knowledge.
