### ISSUE TITLE
Schedule a recurring lang design meeting

### ISSUE THREAD

**Issue by enricosada** [fsharp/fslang-design#46]
I think it's a good idea to have a scheduled recurring ( once a month? every two weeks? weekly? ) meeting to discuss about current proposals status and create actionable items like new pr or issues.
This should help to make the lang design and implementation more fluid and constant 
That's not a way to rush lang implementation

The meeting should focus on one or two proposals at most. That mean new proposals and/or status of current proposal implementation (maybe an implementation pr got stuck with open issues who need answers)

The meeting agenda ( the lang proposals and pr ) should be annunced at least a week before to make it easier for everyone to join meeting prepared for the discussion

In each meeting the owner ( @dsyme obv ) should explain open points of one or two proposals and everyone can propose to:
- make prototype implementation
- new questions
- answers current questions

After each meeting, discussed issues should be labelled with current status and the markdown document about the feature should be updated with accepted changes/questions, so there is a spec and changelog.

We should take notes about the meeting's discussion/actionable items/feedback (like https://github.com/rust-lang/meeting-minutes or https://github.com/dotnet/apireviews ) 

When i say meeting, i dont mean a long open ended discussion. 
I mean a focused discussion on one/two items where everyone know the discussed items and rules. People should come prepared with gist/pr if possibile, to speedup discussion.
Discussion of other issues should not be possible. A facilitator should try to make the meeting short and focused.

**Comment by enricosada** [comment]
Lang proposals require updates to compiler and/or fsharp.core, but i think it's different than a change in API or proposed cleanup/improvement of compiler.

If we want to discuss also API of FSharp.Core or compilers internals, these can be two different meetings.

I'd like to have a different meeting about compiler internals too, issues in visualfsharp are a lot sparse and usually/always without actionable content.
The visualfsharp standup it's about status of current work not discussion of new proposals.

We can try to focus effort on one or two items each week, this should help engage more the community.

**Comment by dsyme** [comment]
@enricosada I need to think this over.  My first goal is to review all items on http://fslang.uservoice.com, being a little bit more proactive in closing off suggestions and reducing to just 100 or so suggestions (from 216 today).  I'll work with @tpetricek on this.

Once items are approved, the biggest problem we seem to have is in circulating draft specifications to high quality and iterating towards a decision.  Meetings can certainly help, but it is very time consuming to write up notes from those.  After specifications, the limiting factor tends to be developing the features to high quality and simplicity with no feature interactions and full IDE support.

Also, I'll admit I personally find it hard to fill both the "designer" and "convenor" roles of the language design process.  The designer role means saying 'No' 95% of the time (honestly - if not 99%).  The convenor wants to make lots of things happen and make everyone happy.  A good language design process needs a very strong convenor who just enjoys running the process even if it takes a long time for things to actually happen :)

I think the thing I'd really like to solve is to have a place where people can post detailed RFCs.  Perhaps this github repo is the place to do that.  But in practice people seem to prefer WIP PRs to github.com/Microsoft/visualfsharp.  I think it would be _much_ easier if the IDE tools were split out of that repo so it could focus on compiler/language/service.

**Comment by dsyme** [comment]
Closing as we do the design process asynchronously, through github discussions
