### ISSUE TITLE
[RFC FS-1086 Discussion] - Public [<Literal>]s as static members

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-design#469]
Discussion for RFC FS-1086 - Public [\<Literal\>]s as static members

Suggestion here: fsharp/fslang-suggestions#746

**Comment by abelbraaksma** [comment]
I think this is the RFC you want to discuss here, right? https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1086-Public-Literals-as-static-members.md

**Comment by abelbraaksma** [comment]
Should we consider local literals as well? I believe that's also currently not possible, and even though let bindings can be compiled as constants by the optimizer, and usually are, they cannot be used in match expressions afaik.

Not sure this is out of scope.
