### ISSUE TITLE
F# Project setting to forbid the use of mutability and explicit use of type null.

### ISSUE THREAD

**Issue by rbrus** [fsharp/fslang-design#476]
Hi Fsharps,

I am working on a project which uses F# only and consumes a lot of C# libraries.

To my suprise after few weeks of coding I have never used mutability, null, class or interface, etc. And I love it.

As this project might grow over the time and more people may be involved in it I would like to keep it as it is now, by preventing use of mutability, explicit nulls, classes, etc, on per project level.
 
What you think?

Best regards,
Radek

**Comment by abelbraaksma** [comment]
Sounds like a good plan, though sometimes you just need mutability, and if you consume data, you'll still have to check for null (or use `Option.ofObj`). It should be rare though. 

It seems though that your title suggests the opposite of your text: permit vs forbid.

**Comment by rbrus** [comment]
I would not like to restrict mutability or nullability. I would like to prevent usage of these features in F# projects (below explained). It would be per project setting, therefore, there should be no impact on any other projects, either projects consuming the library or projects consumed by the library. (Where library is the project with proposed settings turned on).

Explanation:
- Developers cannot use 'null' in the code. However, still can use isNull() to check for nullability. Nullable variables would not change in any way, if something is nullable it would stay nullable, as it is now.
- Prevention of using 'mutable' keyword, anything created in the project must be immutable. Records, Unions, etc. However, consumption of classes and interfaces would not change in any way.
- This one is a lower priority, however, classes and interfaces are a bit messy, especially in F#. Which actually is good, as these concepts don't really fit to F# fundaments I think. The setting, would prevent creation of new classes in the project. (As above, records, unions, etc.).
- Another lower priority (and this one I am struggling to assess the impact but...) add a flag/setting to the project, to prevent using f( , ) type of parameters. I would be happy to prevent using tuple - c# - like parameters and use only 'spaced' F# style parameters.

There could be more settings like this. Imho, this is not just preventing something which can cause problems, or preventing something more specific to other languages, or to keep codebase uniformly, but this is an option to 'clear the language from the clutter'. Yes, clear F# from inaccuracies from C#/.NET which sometimes can be overwhelming by even the need to again and again consider if class is the better option here. No, there are no classes, lets use immutable records, modules, functions, union instead 👍 

'PureImmutableF#Experience'

**Comment by eiriktsarpalis** [comment]
Note that prohibiting either `null` or the `mutable` keyword does not prevent nulls or mutable data from being present in your application. For example in
```fsharp
let xs = [| 1 .. 10 |]
```
the value `xs` might not be mutable, but you can still mutate the contents of what `xs` is referencing:

```fsharp
xs.[0] <- 42
```

You also cannot assume immutability or lack of null returns for almost everything that you might use under the `System.*` namespace.

**Comment by cartermp** [comment]
This isn't something we'd likely ever do. It just bumps too hard into very core design considerations for the language.

**Comment by rbrus** [comment]
> Note that prohibiting either `null` or the `mutable` keyword does not prevent nulls or mutable data from being present in your application. For example in
> 
> ```fsharp
> let xs = [| 1 .. 10 |]
> ```
> 
> the value `xs` might not be mutable, but you can still mutate the contents of what `xs` is referencing:
> 
> ```fsharp
> xs.[0] <- 42
> ```
> 
> You also cannot assume immutability or lack of null returns for almost everything that you might use under the `System.*` namespace.

Exactly that is what I would be happy to have. As I wrote, I don't ask to change a language, or forbid mutability or anything. Just wanted to prevent using the keywords by helping the other devs to not create mutable objects in this particular project that is all.

**Comment by abelbraaksma** [comment]
@rbrus, I think such policies are best enforced by using a linter. Just like an F# linter warns you for forgetting to check for null, you could use (a modified version of) FsLint to check for appearances of null, or any of the other constructs you'd like to forbid.

But as others have already said, this is quite invasive, and limits use of many BCL libraries, creation of optimized code in hot paths, safe consuming of other libraries, create & update of arrays, implementing interfaces (for instance, `IFormattable` is sensible to implement on a DU, but would require tupled arguments, that you seek to prevent), prevents writing overloaded methods (which is only possible with tupled arguments) etc.

I think the idea in general is good, that is, wanting to enforce purer code, but F# lives in a complex ecosystem that requires all of the above to interact. Enforcing company rules on a style of coding really should go in a linter. FsLint is open source and quite easy to adapt.

**Comment by rbrus** [comment]
@abelbraaksma thanks for the answer. Yes, it makes sense. I actually though about writting to Krzysztof Cieslak and if he would see a potential in that create an extension to Ionide, if not do what you suggest extend FSharpLint my self and make it available for anybody interested. 

Thanks for all comments and suggestions.

**Comment by baronfel** [comment]
@rbrus there's no need to make an ionide feature to enforce this. Fsharplint is already integrated into ionide, so if you make an fsharplint rule and check it into your repository ionide will begin enforcing it for you.

**Comment by rbrus** [comment]
@baronfel I didn't have yet time to have a look into FSharpLint. If there are rules it will be even simpler. Thanks for the great hint!
