### ISSUE TITLE
Add support for the new CLI type: half type 

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-design#498]
.NET 5 introduces a new primitive, we should probably add it to our list of primitive your aliases. My suggestion: `half` and/or `float16`.

See:

* https://devblogs.microsoft.com/dotnet/introducing-the-half-type/.
* implementation details: https://github.com/dotnet/runtime/pull/37630 
* proposal: https://github.com/dotnet/runtime/issues/936

**Comment by pblasucci** [comment]
Just a note to say: if/when this work gets done, the work being tracked in #495 should also be extended (it'll be easy-enough).

Also, I'm quite happy with either (or _both_) `half` and `float16`. :+1:

**Comment by abelbraaksma** [comment]
Should've posted it on suggestions, moved it: https://github.com/fsharp/fslang-suggestions/issues/909
