### ISSUE TITLE
[Discussion] [RFC-1092] Add support for System.Half

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-design#500]
This thread is meant to discuss the [proposal RFC-1092](https://github.com/fsharp/fslang-design/blob/75a18a712d37a565a0fd4f99d0dba48b47a1b01d/RFCs/RFC-1092-support-cli-half-type-as-float16.md), see https://github.com/fsharp/fslang-design/pull/499.

This follows language suggestion: https://github.com/fsharp/fslang-suggestions/issues/909.

Unresolved questions atm:

1. Should we add an additional numeric literal suffix?
2. How can we ensure FSharp.Core can be used with this new type in .NET 5.0, but still link to older versions?
3. Should we add overloads like `half: int -> half` and `half: decimal -> half` even though `System.Half` does not define them?

**Comment by abelbraaksma** [comment]
I think I can answer some:

> Should we add an additional numeric literal suffix?

Currently, `System.Half` is implemented as a non-primitive type and uses intrinsics for special processing by the CLR. This leads to problems defining constants (a byte array init is possible, but leads to other issues like endianness). Efforts are underway to provide support for unmanaged types as constants, but not before .NET 5.0.

My verdict: **most likely not**.

> Should we add overloads like half: int -> half and half: decimal -> half even though System.Half does not define them?

They were deliberately excluded from the runtime API proposal on the grounds that they require rounding. Since they are not in the _explicit conversion operators_, implementing it ourselves would undoubtedly lead to differences once the runtime catches up and provides these conversions.

My verdict: **certainly not**.

**Comment by pblasucci** [comment]
I am, thus far, in 100% agreement with @abelbraaksma ... and I’m still “noodling” on the final point (about compatibility with < `Net5`).

**Comment by abelbraaksma** [comment]
@cartermp Since .NET will continue to evolve and the future will see faster increase of versions and, likely, features, we'll need some way to allow a single `FSharp.Core.dll` to reference stuff in future editions of .NET. This is true for `System.Half`, but also for `ImmutableArray` stuff.

I can think of several ways, but each has its drawbacks, here's a little brainstorm:

* Ship multiple versions of FSharp.Core.dll (like `FSharp.Core.net5.dll` etc) and improve magic-linking to pick the right one based on project TFM.
  * Downside: hard to maintain long-term with increasing `#if` directives complexities
  * Unclear how to resolve multi-targeting projects with single source base
* Create additional libs that extend FSharp.Core.dll only linked for older tfm's, like a specific `System.Half.dll` for netcore3.1, but absent for net5.0.
  * Upside: Easy to maintain and develop on a case-by-case basis
  * Downside: increasing set of auxiliary dlls
  * Downside: not all new functionality may be expressible in older .NET versions, esp. if its about intrinsics
* Define a source-level mechanism to create a type alias with an internal attribute like `MinimalTargetFramework("net5.0")` and if another framework is targeted, any consumed function referencing this type will lead to an error or warning.
  * Upside: easy to maintain, easy to extend, can keep single lib FSharp.Core.dll
  * Works largely similar like `ConditionalAttribute`
  * Downside: may be relatively hard change to implement in compiler
* Redefine the types and methods in-house from the runtime sources
  * Upside: no changes in compiler needed, can keep single lib FSharp.Core.dll
  * Downside: may conflict when linking with libs containing actual types, potential missing of intrinsic optimizations of runtime

**Comment by Happypig375** [comment]
So this won't happen for at least a year until FSharp.Core targets net5.0+?

**Comment by dsyme** [comment]
It's my understandng that System.Half can be used directly using the name "System.Half" plus the existing available operators and types

**Comment by dsyme** [comment]
@Happypig375 I've added a note to the RFC proposal here asking for clarification on the status-quo experience. I really believe it is likely to not be that bad, no worse than consuming any other user-defined C# numeric type from F#.

https://github.com/fsharp/fslang-design/pull/499/files#r501840990
