### ISSUE TITLE
can allow `inref` in a byrefLike union?

### ISSUE THREAD

**Issue by greatim** [fsharp/fslang-design#513]
The current rules do not allow, but I think there should be no problem in using `byreflike`? 
Open its use can provide performance optimization

```
[<Struct; IsByRefLike>]
type ValueList<'T> =
   | EndOfList
   | Extract of 'T * inref<ValueList<'T>>
```

**Comment by cartermp** [comment]
No, I don't think we'd want to allow a recursive-ish tree-like structure (but with pointers) to be defined like this.
