### ISSUE TITLE
[RFC FS-1005 Discussion] Underscores in Numeric Literals

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#52]
This issue is used to track discussions of [F# RFC FS-1005 - "Underscores in Numeric Literals"](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1005-underscores-in-numeric-literals.md). Please discuss in thread below (if necessary)

**Comment by 7sharp9** [comment]
Yes!  I would love this, having to type `b100000000000001` can get tricky to spot the exact indexes, its popular in rust too.

**Comment by andredublin** [comment]
:+1: Definitely useful

**Comment by 7sharp9** [comment]
Maybe live code its creation

**Comment by 0x53A** [comment]
@dsyme Are these examples just copy pasted from Java or as-intended?
```
let x9 = 0_52             // OK (octal literal)
let x10 = 05_2            // OK (octal literal)
```

currently in FSI, 0-prefixed literals are still decimal, I think it would be confusing and error prone to change that for underscored literals:
```
> 010;;
val it : int = 10
> 0o10;;
val it : int = 8
> 
```

Beside that, +1, that feature would make some code soo much more readable.

**Comment by dsyme** [comment]
Thanks @0x53A - yes, copy error. Please send a PR to correct this?

**Comment by neoeinstein** [comment]
Closing as no new comments and now complete.
