### ISSUE TITLE
[RFC FS-1006 Discussion] Struct Tuples and Interop with C# 7.0 Tuples

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#53]
This issue is used to track discussions of [F# RFC FS-1006 - "Struct Tuples and Interop with C# 7.0 Tuples"](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1006-struct-tuples.md). Please discuss in thread below. Please send PRs to the RFC if you propose an adjustment, improvement or correction to the RFC.

**Comment by smoothdeveloper** [comment]
First, it's a great thing that those features are being considered along with what C# will be doing!

Should there be support in `FSharp.Core` to convert between struct and nonstruct types? I'm thinking the same way `Option` has suppport to convert from / to `Nullable<'t>`.

**Comment by dsyme** [comment]
@smoothdeveloper Good question.  In principle yes.  However it's possible we will need to avoid FSharp.Core having _any_ dependency on System.StructValue in the first place, I'm not sure - these types aren't in .NET 4.6, and FSharp.Core can be used with .NET 4.5 and above.  If they first appear in .NET 5.0 then I'm not sure what we're going to do.  The C# design doesn't answer this somewhat fundamental question :)

**Comment by dsyme** [comment]
I have added a link to an experimental spike implementing this feature.  It needs plenty of polish and testing, but [this gist](https://gist.github.com/dsyme/0f3c6e5ac3d9f5e2d723) works and gives the expected 14x performance improvement for this pathologically good case:

Took 1054.3436 ms
Took 70.4085 ms

Took 842.637 ms
Took 70.9176 ms

Took 839.3326 ms
Took 69.9412 ms

Took 833.0841 ms
Took 77.6221 ms

Took 822.7966 ms
Took 84.8841 ms

Took 771.5723 ms
Took 68.9288 ms

Took 788.2285 ms
Took 70.3147 ms

Took 865.3489 ms
Took 70.6449 ms

Took 834.1691 ms
Took 71.4205 ms

Took 779.2969 ms
Took 70.4884 ms

Took 845.6452 ms
Took 70.4169 ms

**Comment by smoothdeveloper** [comment]
@dsyme please name your fsharp files `.fsx` in gist, sorry to be nagging about formatting all the time :)

**Comment by smoothdeveloper** [comment]
@dsyme how does this affect tuples that can be defined in DU?

```fsharp
type ParsedImplFileInput = 
    | ParsedImplFileInput of string * (*isScript: *) bool * QualifiedNameOfFile * ScopedPragma list * ParsedHashDirective list * SynModuleOrNamespace list * bool
```

could this be turned into struct tuple this way:


```fsharp
type ParsedImplFileInput = 
    | ParsedImplFileInput of struct (string * (*isScript: *) bool * QualifiedNameOfFile * ScopedPragma list * ParsedHashDirective list * SynModuleOrNamespace list * bool)
```

**Comment by dsyme** [comment]
@smoothdeveloper Those are not strictly speaking tuples unless you parenthesize (they are stored "flat" inside the object instance).  This is the same approach as OCaml and has an effect in a number of places, e.g. in pattern matching you can't use a single value to match a bunch of values ``match x with X tup -> ...``

```fsharp
type X = 
    | X of (int * int * int)
```

But yes, you could use a struct tuple like you mention, but there's not much point in doing so since the representation is already flattened.

**Comment by gafter** [comment]
In this draft doc, it says

> ### Type equivalence
> 
Two tuple types are only equivalent if they have the same structness (**and named argument metadata if that feature is supported**)

(emphasis mine)

However, for C# we are proposing that the names do not participate in whether two tuple types are the same or not. Or alternately, there will be something like an identity conversion between tuple types that differ only by name.

I don’t know if that would be challenging for F#, but that’s what we plan for C#.

**Comment by dsyme** [comment]
@gafter Thanks Neal for those details!  Either would be possible for F# (as would emitting a warning,  or just ignoring field metadata initially).

**Comment by smoothdeveloper** [comment]
> An alternative is to adjust the F# compiler and specification so that F# tuples are always compiled as structs, or some other variation on this. This option has been discarded since it would be a breaking change to the binary compatibility of F# code.

For compiled binaries, I assume the compatibility can be preserved.

I know compiler options are kind of a bane, but I'm wondering if the more verbose notation for tuples is not going to hurt their adoption?

Maybe introducing a syntax to define reference type tuples as well would allow library authors to go over and specify explicitly if struct or reference is desired in a compatible manner, also have an optional warning to highlight all places where it is not explicitly defined; and after next major version make the switch to struct tuple for the terse notation?

**Comment by rpolton** [comment]
Hi, strictly as an observer, but can I ask why the struct tuple type is being given a new keyword but the struct record et al. types are annotated with [<Struct>]? From an outsider's perspective it seems cleaner to use the annotation throughout.

**Comment by toburger** [comment]
Also on hackernews there is some discussion going on regarding the syntax: https://news.ycombinator.com/item?id=12184041

**Comment by ghord** [comment]
Would you consider an attribute on the project/module level that makes all tuples be struct tuples? It seems that with proposed syntax it will be easier to use struct tuples in C# than F#.

**Comment by dsyme** [comment]
@ghord It's possible additions will be needed - inferring structness is the most likely thing.

I think the importance of further improvements like this depends partly on how much tuples start to appear at API boundaries, and how much people find major performance benefits in routine code (and hence start to use struct tuples).  For the vast majority of code ref tuples are good (and in some cases they improve performance over struct tuples because of less copying)

Also there are other constraints besides syntax to the more pervasive use of struct tuples in F#, especially the fact that some F# core library functions take and produce ref tuples (e.g. Seq.zip and Seq.unzip).  

p.s. This RFC is done - we should probably consider any extensions in a separate RFC.

**Comment by neoeinstein** [comment]
Closing with no new comments and now complete.
