### ISSUE TITLE
F# Community design/implementation/test review for resumable code and tasks

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#557]
Time: Monday 17th May 2021, 2000 UK BST 

Where: Microsoft teams link will be provided on this issue before the call

Scheduling time for an open community call for a design/implementation/test review on resumable code and tasks

Here are the links to the RFCs 

[RFC FS-1087 resumable code](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1087-resumable-code.md)

[RFC FS-1097 task builder](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1097-task-builder.md)

[RFC FS-1098 inline if lambda](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1098-inline-if-lambda.md)

[F# Tooling RFC FST-1034 – additional lambda optimizations](https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1034-lambda-optimizations.md)

**Comment by heronbpv** [comment]
Will this be made available later at the youtube channel?

**Comment by baronfel** [comment]
Link to the time in your time zone: https://mytime.io/8pm/UTC

For reference, this is 3PM US Central Time.

**Comment by NinoFloris** [comment]
@baronfel small mistake, BST is UTC + 1 (British Summer Time, not GMT) so => https://mytime.io/8pm/BST

**Comment by baronfel** [comment]
You didn't see _anything_. There never was any mistake at all.

**Comment by dsyme** [comment]
Teams link (we're starting in an hour from now)

https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzcyNjI1ZTgtYWFkYS00NDBlLThjYmQtOWI5ODFhZmQyNmRl%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%22e374a10e-9340-46d0-a4be-5af5ac3602d5%22%7d

I will try to record, I've not done it before and may mess it up

**Comment by NatElkins** [comment]
Was the meeting recorded after all?

**Comment by vzarytovskii** [comment]
> Was the meeting recorded after all?

Yes. I will upload it to the FSSf YT channel and post the link here.

**Comment by NatElkins** [comment]
@vzarytovskii Just wanted to check in on this.

**Comment by vzarytovskii** [comment]
> @vzarytovskii Just wanted to check in on this.

I've uploaded it, need to lightly edit it and will publish it. Gonna probably do it tomorrow morning (or today evening).

**Comment by dsyme** [comment]
Thanks everyone for attending this review, it was extremely useful, as was the subsequent in-depth code review by @NinoFloris 

I'd encourage everyone who attended or who watched the video to do submit their own line-by-line code review of the implementation at https://github.com/dotnet/fsharp/pull/6811/

**Comment by vzarytovskii** [comment]
Video is available on the YT channel, by the way: https://www.youtube.com/watch?v=B6m_vJ-a2dM
