### ISSUE TITLE
F# Community design/implementation review - Additional type directed conversions

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#589]
Time: Tuesday 8th June 2021, 2000 UK BST

Where: Teams link will be provided below on this issue before the call

Scheduling time for an open community call for a design/implementation/test review on [RFC FS-1093 Additional type directed conversions](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1093-additional-conversions.md). The implementation and testing is here: https://github.com/dotnet/fsharp/pull/10884

**Comment by vzarytovskii** [comment]
This is working link to RFC: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1093-additional-conversions.md

**Comment by dsyme** [comment]
Teams link: https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGRiMzhhMjMtYWIxMy00YTI3LWJjZjEtMGRkZDI2MmE1NDhm%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%22e374a10e-9340-46d0-a4be-5af5ac3602d5%22%7d
