### ISSUE TITLE
[style-guide] Units of measure should format like expressions 

### ISSUE THREAD

**Issue by sonicbhoc** [fsharp/fslang-design#660]
There are no guidelines for units of measure. Due to this, the Fantomas team does not have guidance for formatting them, which leads to oddities such as those seen in fsprojects/fantomas#2207. Please add guidelines for formatting units of measure.

**Comment by nojaf** [comment]
Hello @dsyme, the problem space here is that Fantomas currently produces this:
```fsharp
type Test =
    { WorkHoursPerWeek: uint<hr / (staff weeks)> }
    static member create = { WorkHoursPerWeek = 40u<hr/(staff weeks)> }
```

Where there are spaces around the `/` in the type definition but not when used in the measure instance. 
Any thoughts?

**Comment by smoothdeveloper** [comment]
🎉 
```fsharp
type Test =
    { WorkHoursPerWeek: uint< hr / (staff weeks) > }
    static member create = { WorkHoursPerWeek = 40u< hr / (staff weeks) > }
```
🚀 
```fsharp
type Test =
    { WorkHoursPerWeek: uint<hr / (staff weeks)> }
    static member create = { WorkHoursPerWeek = 40u<hr / (staff weeks)> }
```
👀
```fsharp
type Test =
    { WorkHoursPerWeek: uint<hr/(staff weeks)> }
    static member create = { WorkHoursPerWeek = 40u<hr/(staff weeks)> }
```

**Comment by nojaf** [comment]
Hi @smoothdeveloper, I appreciate your idea of creating a poll, but I think we should try to keep this a constructive debate with arguments about why a certain style fits better in the overall story of the style guide rather than just voting away.

**Comment by auduchinok** [comment]
The third variant may seem a bit "prettier" with shorter measure types, but the second one (i.e. with spaces around `/`) is more inline with the rest of the guide for various language parts so I'd vote for it.

**Comment by dsyme** [comment]
> The third variant may seem a bit "prettier" with shorter measure types, but the second one (i.e. with spaces around /) is more inline with the rest of the guide for various language parts so I'd vote for it.

I agree, this looks right to me

**Comment by sonicbhoc** [comment]
Looks good to me.
