### ISSUE TITLE
[style-guide] Guidance for code quotations

### ISSUE THREAD

**Issue by dawedawe** [fsharp/fslang-design#661]
Currently the F# style guide lacks guidance for code quotations. This causes issues for Fantomas.
See [2211](https://github.com/fsprojects/fantomas/pull/2211) for more background, especially nojaf's [example](https://fsprojects.github.io/fantomas-tools/#/?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQA8AAgDoAnPsggQasAC5gAtmgDmYALxgApAAsJEgA4AlWAEcArugkBZdGipzYAdUQS1ABSoBPGqyrQwAem9gALGDinigKaFpUzOiCwqJgOobIEojSsAASsDRasAJoAHRINDQZnjloMvKqarCe5b4BQTXQoWDhkdFCIqJUaC7IzGDAPn6Bwc3IYRFRaDFdcWKSAIRgAuharMj0SmAAFCoORACUeWmaWgDCNIiwSXkAyjfQAIK9-TuycodgAD4AfGAvPrMPJPADuVHsABUegBrYZgAAcjRCE1aUw6sXmEFWEkMAhEq3CG3oeQAops8bA7oZmNM0HcJFRcWhzuxYDtjqykjcpPUkWMWm1prM4gBfeGjJqC9EzTo8X6zWb1J5FZHjSbtcqraQQkRUETSQw0ZK4uBgVjwMAOWBgFBwJIAfTIAC9YIrOrxGlIPtt1Gc9EYTOY0JZrHYHM43B5oCKIAkkil0plsrkCogiiU4LkKgp1E06n4AMxq6WasCxsA9IGDeHFgWooUYuZxcQSZaE9abG3KeoAdhLDZlFaxED2BzQx1O2ku11uD2Qz1ezHe8i%2B9QAjOuBxrhZ0R3E-gClyDwVDYfDN9u0Zrh6IcXiCWtibAyRTVtTaRYGUzDCy2Ry8i5CQeXhft6x3JsxTAeV3WEeo7lYVIr0bcoqFWKAQFFIA).

So let's change that.
We suggest to put the delimiter symbols (`<@` , `@>`, `<@@`, `@@>`) on separate lines if the quoted expression is a multi-line expression like:
```fsharp
<@
    let f x = x + 10
    f 20
@>
```
and to keep everything in one line for single-line expressions like:
```fsharp
<@ 1 + 1 @>
```
(Assuming the expression fits in one line.)
The [language reference](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/code-quotations) is using this style for the most part, too.
I'd be happy to create the needed pull requests after we have come to a conclusion on this issue.

**Comment by dsyme** [comment]
I agree with this
