### ISSUE TITLE
nullness implementation error

### ISSUE THREAD

**Issue by RealmPlume** [fsharp/fslang-design#791]
```
   let foo(x:'T | null) = ()

   let foo2(x:'X when 'X: null) = foo x

   let foo3 (x:'T when 'T: not struct) = foo x
```
Here is the compile warning FS3261

We expect that no warning will be issued for either `foo2` or `foo3`.

and:
```
      let dic = Dictionary<'key,'value>()
      let mutable exist = false
      let ref = &CollectionsMarshal.GetValueRefOrAddDefault(dic, "SomeKey", &exist)
```
when `'value` needs to be compatible with struct and class, 
there is no way to avoid the warning here, unless you block FS3261.

**Comment by vzarytovskii** [comment]
This should be reported to fsharp repo
