### ISSUE TITLE
[RFC FS-1012 Discussion] Support for caller info attributes

### ISSUE THREAD

**Issue by latkin** [fsharp/fslang-design#84]
Opening this to track discussion of [RFC FS-1012 - Support for caller info attributes](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1012-caller-info-attributes.md)

**Comment by dsyme** [comment]
Added some material to the RFC here: https://github.com/fsharp/FSharpLangDesign/pull/86

**Comment by eiriktsarpalis** [comment]
Great feature! Would this potentially also include support for computation expression methods accepting caller info attributes?

**Comment by dsyme** [comment]
@eiriktsarpalis Added that as an unresolved question in the RFC here: https://github.com/fsharp/FSharpLangDesign/pull/87

**Comment by eiriktsarpalis** [comment]
Also related: https://fslang.uservoice.com/forums/245727-f-language/suggestions/13499082-add-support-for-symbolic-stacktraces-in-computatio

**Comment by latkin** [comment]
We will add additional tests covering the open items.  Thanks for the suggestions.

**Comment by dsyme** [comment]
Closing as RFC has been accepted in F# 4.1. Discussion may still continue on this thread.
