### ISSUE TITLE
[RFC FS-1015] Support for "fixed"

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#99]
This is the discussion thread for [RFC FS-1015 Support for "fixed"](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1015-support-for-fixed.md), if discussion is needed

I've started the implementation here: https://github.com/Microsoft/visualfsharp/compare/master...dsyme:fixed, no PR as yet

**Comment by mexx** [comment]
Just to clarify, as like with the `use` binding right now, it shouldn't be possible to pattern match on the value in the same declaration, right?

**Comment by dsyme** [comment]
@mexx Correct.

- Single identifier "use x = fixed ..."
- No actualy IDisposable object gets allocated

**Comment by dsyme** [comment]
Closing as RFC has been accepted
